workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG'

run-fossid-diffscan:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
    
  stage: scan
  image:
    name: quay.io/fossid/fossid-toolbox:latest
    entrypoint: [""]
  script:
    - |
      fossid \
      diffscan \
      --fossid-host $FOSSID_HOST \
      --fossid-token $FOSSID_TOKEN \
      --fail 1
