# This workflow will run ORT's Analyzer then upload the analyzer-result.json it produces into Workbench.
name: Upload ORT Results to Workbench 

on: workflow_dispatch

jobs:
  run-ort-upload-results:
    runs-on: ubuntu-latest
    env:
      WORKBENCH_URL: ${{ secrets.WORKBENCH_URL }}
      WORKBENCH_USER: ${{ secrets.WORKBENCH_USER }}
      WORKBENCH_TOKEN: ${{ secrets.WORKBENCH_TOKEN }}
    steps:
    - name: Run ORT GitHub Action
      uses: oss-review-toolkit/ort-ci-github-action@v1
      with:
        allow-dynamic-versions: 'true'
        run: >
          analyzer
          
    - name: Confirm the Analyzer JSON was created
      run: ls -la /home/runner/.ort/ort-results

    - name: Checkout FossID Scripts Repo
      uses: actions/checkout@v4
      with: 
        repository: fossid-ab/workbench-api-samples

    - name: Upload ORT Results to Workbench
      run: |
        python import-da/import-da.py \
        --api-url ${{ secrets.WORKBENCH_URL }} \
        --api-user ${{ secrets.WORKBENCH_USER }} \
        --api-token ${{ secrets.WORKBENCH_TOKEN }} \
        --scan-code $GITHUB_REPOSITORY/$GITHUB_HEAD_REF \
        --file "/home/runner/.ort/ort-results/analyzer-result.json"
